### ISSUE TITLE
ABAP Statements: REDUCE

### ISSUE THREAD

**Issue by nocin** [Xexer/abap-feature-matrix#1]
Hi,

thanks for this great overview! Perhaps, the REDUCE keyword can be added to the ABAP statements?
Often had problems with the command on different systems due to different release statuses. Would therefore certainly be a useful addition. :-)

BR,
Nico

**Comment by Xexer** [comment]
Hi Nico,
will add this, thank you for your suggestion.
Greetings
Björn

**Comment by Xexer** [comment]
Command was added
