### ISSUE TITLE
Missing SAP Docu Links

### ISSUE THREAD

**Issue by ruthiel** [Xexer/abap-feature-matrix#2]
Hello @Xexer !
I'd like to contribute to this project in some way.

I noticed that there are some missing SAP Docu links for some of the features, like:
<img width="993" alt="image" src="https://github.com/user-attachments/assets/1311b756-ebfd-4231-a72d-43814d3c4c65">

Would it be a legit improvement if I could suggest some links for it?

I can understand that for some of them maybe it makes no sense to add it since they are really specific.
Let me know if I can help with it!

**Comment by Xexer** [comment]
Hi @ruthiel,
all help is welcome. If you find a missing link (there are some at the moment), you have three options:
- Create a PR via GitHub to fix the link directly
- Post the suggested links in the issue
- When I have time, I'll seach for the links and insert them

And thank you for the issue, there are some things to do here.

Greetings
Björn
